### ISSUE TITLE
events

### ISSUE THREAD

**Issue by behiunforgiven** [CalvinEng/NFC-Plugin#1]
Hi Calvin
thanks a lot for your plugin.
what are the events ? (like onTagDetect and etc...)

**Comment by CalvinEng** [comment]
@behiunforgiven what you are looking for is the onNewIntent fuction which is triggered when a tag is scanned. As my plugin is only designed for the NTAG series, it may not match what you want. I recommend you also look at the nxp nfc library if you see some features that I may not implemented or for different kind of tags.

**Comment by hruizdev** [comment]
Hi @CalvinEng, 
Do you have some phonegap example to show functionality of this plugin?.

**Comment by CalvinEng** [comment]
Hi @chompirax, I do not have a example as this is actually designed for a very specific use for my work and didn't actually plan to share it with the public. However if u look at the nfc.js file in the www folder of my plugin, which is the file linking the javascript code to the java code, it shows how to call the functions in phonegap. For example, this is the init function:

init: function (user, url, successCallback, errorCallback) {
        cordova.exec(successCallback, errorCallback, "Nfc", "init", [user, url]);
    },

From this, you can call the function by passing in the correct parameters like this:

 nfc.init(user, url, function (nfcMsg) {
               //initialisation sucess, implement subsequent task here.
            },
            function () {
                /initialisation fail, output errro message.
            });

I hope this helps, feel free to ask me any question if you encounter any problems and I hope I can answer you,
